name: Workflow Lint

on:
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'
  push:
    branches: [master]
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

jobs:
  actionlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: true
